on:
  pull_request:
    branches:
    - "truckin/release"
    types: [closed]

jobs:
  auto-delete:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          exclude: "main, master, truckin/*"
          delete_closed_pr: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
