# This is a basic workflow to help you get started with Actions

name: Auto-Delete Release PR Branch

on:
  pull_request:
    branches:
    - "truckin/release"
    types: [closed]

jobs:
  auto_delete:
    runs-on: ubuntu-latest
    steps:
      - run: echo "source branch => ${{ github.head_ref }}"
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with: 
          exclude: "['main', 'truckin/*']"
          delete_closed_pr: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
