# This is a basic workflow to help you get started with Actions

name: Auto-Delete Release PR Branch

on:
  pull_request:
    branches:
    - "truckin/release"
    types: [closed]

jobs:
  auto-delete:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
